name: gradle-build
on:
  pull_request:
    branches: [ "*" ]

jobs:
  gradle:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            gradle-
      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew
      - run: |
          ./gradlew clean build
